# -*- coding: utf-8 -*-


SPONSOR_TYPE_PLATINUM = 1
SPONSOR_TYPE_GOLD = 2
SPONSOR_TYPE_SILVER = 3
SPONSOR_TYPE_BRONZE = 4

SPONSOR_TYPES = (
    (SPONSOR_TYPE_PLATINUM, 'platin'),
    (SPONSOR_TYPE_GOLD, 'altın'),
    (SPONSOR_TYPE_SILVER, 'gümüş'),
    (SPONSOR_TYPE_BRONZE, 'bronz'),
)