from __future__ import unicode_literals

ADMINISTRATIVE_NOTE_GRAY = 1
ADMINISTRATIVE_NOTE_BLACK = 2

ADMINISTRATIVE_NOTE_TYPES = (
    (ADMINISTRATIVE_NOTE_GRAY, "Gri"),
    (ADMINISTRATIVE_NOTE_GRAY, "Kara"),
)
